cat header > $(date +%F)-finset-and-its-up.md
cat header > $(date +%F)-p-and-its-up-and-species.md
cat header > $(date +%F)-monoidal-structures-on-P.md
cat header > $(date +%F)-species-and-analytic-functors:-wide-pullbacks.md
cat header > $(date +%F)-examples-of-species.md
cat header > $(date +%F)-cayleys-theorem-from-joyal-paper.md
cat header > $(date +%F)-species-in-combinatorics-fp-topology-algebra.md
cat header > $(date +%F)-species-and-operads.md
cat header > $(date +%F)-linear-species-linear-operads.md
cat header > $(date +%F)-differential-2-rigs,-a-crash-course.md
cat header > $(date +%F)-derivation-on-species-and-its-adjoints.md
cat header > $(date +%F)-the-chain-rule-for-species-and.md
cat header > $(date +%F)-taylor-formula-for-species.md
cat header > $(date +%F)-differential-equations.md
cat header > $(date +%F)-yeh-decomposition-theorem.md
cat header > $(date +%F)-vistas-for-the-future.md